server:
    port: 8081
spring:
    application:
        name: kafka-rss-feed-consumer
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: rss-feed-consumer-group
            auto-offset-reset: earliest
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
              show_sql: false